export enum ModalNames {
  COMPLETE_REGISTRATION = "CompleteRegistration",
  ACCEPT_REGISTRATION = "AcceptRegistration",
  SEARCH_CONFLICTS_FILTERS = "SearchConflictsFilters",
  FIRST_INSTANCE = "FirstInstance",
  SECOND_INSTANCE = "SecondInstance",
  REVISION = "Revision",
  DEFINITION = "Definition",
  CONFLICTS_GRANT_EXTENSION = "ConflictGrantExtension",
  CONFLICTS_CONFIRM_PERCENTAGE = "ConflictConfirmPercentage",
  CONFLICTS_SEND_DOCUMENTATION = "ConflictSendDocumentation",
  CONFLICTS_DESIST = "ConflictDesist",
  CONFLICTS_ACCEPT = "ConflictsAccept",
  EXPORT_CHANGES_LIST = "ExportChangesList",
  FINISH_NEW_PHONOGRAM = "FinishNewPhonogram",
  TERRITORIALITY_SAVE = "TerritorialitySave",
  SUBMIT_SEND_APPILICATION = "SubmitSendApplication",
}
