export enum ModalNames {
  COMPLETE_REGISTRATION = "CompleteRegistration",
  ACCEPT_REGISTRATION = "AcceptRegistration",
  SEARCH_CONFLICTS_FILTERS = "SearchConflictsFilters",
  FIRST_INSTANCE = "FirstInstance",
  SECOND_INSTANCE = "SecondInstance",
  REVISION = "Revision",
  DEFINITION = "Definition",
  CONFLICTS_GRANT_EXTENSION = "ConflictGrantExtension",
  CONFLICTS_CONFIRM_PERCENTAGE = "ConflictConfirmPercentage",
  CONFLICTS_SEND_DOCUMENTATION = "ConflictSendDocumentation",
  CONFLICTS_DESIST = "ConflictDesist",
  CONFLICTS_ACCEPT = "ConflictsAccept",
  CASHFLOW_PAYOUTS_MATCH_REPORT = "CashflowPayoutsMatchReport",
  CASHFLOW_PAYOUTS_IMPORT_PAYOUTS = "CashflowPayoutsImportPayouts",
  CASHFLOW_PAYOUTS_EXPORT_PAYOUTS = "CashflowPayoutsExportPayouts",
  CASHFLOW_TRANSFERS = "CashflowTransfers",
  CASHFLOW_TRANSFERS_EXPORT = "CashflowTransfersExport",
  CASHFLOW_IMPORT_PAYMENT = "CashflowImportPayment",
  CASHFLOW_EXPORT_PAYMENTS = "CashflowExportPayments",
  CASHFLOW_IMPORT_REJECTIONS = "CashflowImportRejections",
  CASHFLOW_EXPORT_REJECTIONS = "CashflowExportRejections",
  CASHFLOW_EXPORT_REJECTIONS_REVERSE_PAYMENT = "CashflowExportRejectionsReversePayment",
  EXPORT_CHANGES_LIST = "ExportChangesList",
  FINISH_NEW_PHONOGRAM = "FinishNewPhonogram",
  TERRITORIALITY_SAVE = "TerritorialitySave",
  SUBMIT_SEND_APPILICATION = "SubmitSendApplication",
}
