name: Automatic CI

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_COMMIT_MESSAGE: Automatic CI for push on main and Docker Hub

jobs:
  docker_front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NEXT_PUBLIC_API_URL: "http://capif-back:3000/api/v1/"
      NEXT_PUBLIC_PORT: "3001"
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: "6LfZctYqAAAAAHj9_CL9_vfv-2okXZ7ccGwBefqs"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Get Version
        id: version
        run: echo "NEW_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push Frontend Image
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
          --build-arg NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT} \
          --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY} \
          -t javiertrombetta/capif-front:$NEW_VERSION .
          docker tag javiertrombetta/capif-front:$NEW_VERSION javiertrombetta/capif-front:latest
          docker push javiertrombetta/capif-front:$NEW_VERSION
          docker push javiertrombetta/capif-front:latest
