name: Automatic CI

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_COMMIT_MESSAGE: Automatic CI for push on main and Docker Hub

jobs:
  docker_front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Get Version
        id: version
        run: echo "NEW_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push Frontend Image
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
          docker build -t javiertrombetta/capif-front:$NEW_VERSION .
          docker tag javiertrombetta/capif-front:$NEW_VERSION javiertrombetta/capif-front:latest
          docker push javiertrombetta/capif-front:$NEW_VERSION
          docker push javiertrombetta/capif-front:latest
